### ISSUE TITLE
Should here be Discrete(2) ?

### ISSUE THREAD

**Issue by gaoyuankidult** [JKCooper2/gym-bandits#3]
https://github.com/JKCooper2/gym-bandits/blob/9376004939df952036f9ea2ad3269b90774ee573/gym_bandits/bandit.py#L34

Hi, 

In this case, we have two actions.  I wonder should here be Discrete(2) instead of Discrete(1)? The gym document indicates that actions are defined to range from 0 to the number in the bracket. 

Thanks for your time and consideration on this matter!

Best,

**Comment by JKCooper2** [comment]
I think Discrete(1) is correct as the observeration is always 0, as bandit problems are single step
